name: assistant

services:
  api:
    build:
      context: ./assistant_api
    container_name: assistant_api
    entrypoint: >
      sh -c "poetry run gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind unix:/tmp/fastapi.sock main:app"
    restart: unless-stopped
    volumes:
      - api_socket:/tmp
      - logs:/app/logs
    ports:
      - 8000:8000
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--unix-socket", "/tmp/fastapi.sock"]
      interval: 10s
      timeout: 5s
      retries: 3

  proxy:
    image: nginx:alpine
    container_name: notification_proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - logs:/etc/nginx/logs
      - api_socket:/tmp
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/nginx_status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  api_socket:
  logs:

networks:
  movies_project_net: