@startuml "Обращение пользователя к Алисе с запросом на поиск"
autonumber

title Обращение пользователя к Алисе с запросом "кто автора фильма Звездные войны"
actor User
boundary YandexDialogs
participant API
participant DialogueController
participant Assistant
participant ReplyGenerator
participant ServicesInteractor
participant MoviesInterface
participant DialogKeeper
boundary MoviesAPI
boundary Dialogs

' Начало процесса

User -> YandexDialogs++: "Кто режиссер\nфильма звёздные\nвойны 1984 года"
YandexDialogs -> API++: Webhook\njson/http
API -> DialogueController++: webhook, assistant=Alice
DialogueController -> Assistant++: Сессия новая?
Assistant --> DialogueController: нет
DialogueController -> Assistant: Запрос интентов\nиз webhook
Assistant --> DialogueController: интенты c формами
DialogueController -> ServicesInteractor ++: интент "поиск персоны", заполненная форма
ServicesInteractor -> MoviesInterface ++: Формирование запроса
MoviesInterface -> MoviesAPI ++: отправка запроса в сервис
MoviesAPI -> MoviesInterface --: результат поиска
MoviesInterface -> ServicesInteractor --: результат поиска
ServicesInteractor -> DialogueController --: результат поиска
DialogueController -> ReplyGenerator ++: Подстановка результата в шаблон ответа
ReplyGenerator -> DialogueController --: Фраза
DialogueController -> API --: Фраза, state
API -> Assistant: подготовь response: фраза, state
Assistant -> API --: AliceResponse
API -> YandexDialogs: AliceResponse
YandexDialogs -> User --: текст
== Сохранение диалога ==
API -> DialogKeeper ++: Сохранить диалог
DialogKeeper -> Dialogs ++: POST Dialog
Dialogs --> DialogKeeper --: Created
DialogKeeper --> API --: Created
deactivate API
@enduml