@startuml "Первое обращение пользователя к навыку"
autonumber

title Первое обращение пользователя к навыку
actor User
participant API
participant DialogueController
participant Assistant
participant ReplyGenerator
participant DialogKeeper
boundary Dialogs

' Начало процесса

User -> API++: Webhook
API -> Assistant++: Инициализация экземпляра\nAssistant("Alice", webhook)
API -> DialogueController++: передача созданного экземпляра Assistant
DialogueController -> Assistant: Запрос интентов
Assistant --> DialogueController: "приветствие"
DialogueController -> Assistant: Сессия новая?
Assistant --> DialogueController: да
DialogueController -> Assistant: Пользовался пользователь\nранее навыком?
opt
Assistant --> DialogueController: <font color=green> да
DialogueController -> ReplyGenerator ++: Запрос фразы для приветствия\n<font color=green>существующего</font> пользователя
else
Assistant --> DialogueController: <font color=red> нет
DialogueController -> ReplyGenerator ++: Запрос фразы для приветствия\n<font color=red>нового</font> пользователя
end
ReplyGenerator -> DialogueController --: Фраза
deactivate ReplyGenerator
DialogueController -> Assistant: Подготовь ответ с учетом\nповерхности и фразы
Assistant -> DialogueController --: ANSWER_TO_USER
DialogueController -> API --: ANSWER_TO_USER
API -> User: ANSWER_TO_USER

API -> DialogKeeper ++: Сохранить диалог
DialogKeeper -> Dialogs ++: POST Dialog
Dialogs --> DialogKeeper --: Created
DialogKeeper --> API --: Created
deactivate API
@enduml