debug = false

reply_text_length_limit = 300

movies_api_host = "movies.proxy"
movies_api_port = "80"

mongo_dsn_1 = "mongodb://mongos1:27017"
mongo_dsn_2 = "mongodb://mongos2:27017"
mongo_db_name = "aliceDB"
mongo_dialogue_collection = "dialogueCollection"

[timeouts]
generate_response = 1.0
movies_api_response = 0.5

[tracing]
tracing = true
tracing_host = "assistant.jaeger"
tracing_port = 6831

[logger]
logging_level = 20
max_bytes = 1048576
backup_count = 5
