debug = true
# movies_api_host = "movies.proxy"
movies_api_host = "localhost"
# movies_api_port = "80"
movies_api_port = "8001"

tracing = true
tracing_host=auth.tracing
tracing_ui_port=16686
tracing_port=6831


# mongo_dsn_1 = "mongodb://mongos1:27017"
# mongo_dsn_2 = "mongodb://mongos2:27017"
mongo_dsn_1 = "mongodb://localhost:27019"
mongo_dsn_2 = "mongodb://localhost:27020"
mongo_db_name = "aliceDB"
mongo_dialogue_collection = "dialogueCollection"

[timeouts]
generate_response = 1.0
movies_api_response = 0.5
