debug = true
movies_api_host = "localhost"
movies_api_port = "8001"

mongo_dsn_1 = "mongodb://localhost:27019"
mongo_dsn_2 = "mongodb://localhost:27020"
mongo_db_name = "aliceDB"
mongo_dialogue_collection = "dialogueCollection"
