"""Oauth_user create table & contraint

Revision ID: 0b2b4c10cfd5
Revises: 76b06a0ad162
Create Date: 2024-05-07 22:30:45.292905

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b2b4c10cfd5"
down_revision: Union[str, None] = "76b06a0ad162"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=10), nullable=False),
        sa.Column("provider_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(
        "unique_oauth_link_to_user",
        "oauth_user",
        ["user_id", "provider_user_id", "provider"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_user")
    op.drop_constraint(
        "unique_oauth_link_to_user", "oauth_user", type_="unique"
    )
    # ### end Alembic commands ###
